# Autogenerated wrapper script for libavtp_jll for x86_64-linux-gnu
export libavtp

JLLWrappers.@generate_wrapper_header("libavtp")
JLLWrappers.@declare_library_product(libavtp, "libavtp.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libavtp,
        "lib/libavtp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
